name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_ci_db
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: test_ci_user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: 
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run test suites
        env:
          PGDATABASE: test_ci_db
          PGHOST: localhost
          PGPASSWORD: postgres
          PGUSER: test_ci_user
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm t
